swagger: '2.0'

info:
  version: "1.0.0"
  title: NSF

host: localhost
basePath: /lraeval/api/nsf
schemes:
  - http
produces:
  - application/json

x-prefixes:
  - prefix: rdf
    url: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  - prefix: dc
    url: http://purl.org/dc/terms/
  - prefix: nsf
    url: http://www.nsf.gov/terms/
  - prefix: vivo
    url: http://vivoweb.org/ontology/core#
  - prefix: bibo
    url: http://purl.org/ontology/bibo/
  - prefix: foaf
    url: http://xmlns.com/foaf/0.1/

paths:
  /awards.json:
    get:
      summary: Search awards
      description: The NSF Awards API allows users to build a query based on any of the parameters below

      x-type: ReadAction
      x-graphPattern: >
        ?grant a vivo:Grant ;
          nsf:id ?grantId ;
          dc:title ?grantTitle ;
          dc:date ?grantDate ;
          vivo:totalAwardAmount ?amount ;
          vivo:grantAwardedBy ?agency ;
          vivo:relates ?institution ;
          vivo:relates ?person .
        ?person a foaf:Person ;
          foaf:givenName ?personFirstName ;
          foaf:familyName ?personLastName ;
          foaf:name ?personName .
        ?institution a foaf:Organization ;
          foaf:name ?institutionName .
        ?agency a foaf:Organization ;
          foaf:name ?agencyName .

      tags:
        - Search

      parameters:
        # Keyword
        - name: keyword
          in: query
          description: Free text search across all the available awards data
          required: false
          type: string
          x-graphVar: ?grantTitle

        # Id
        - name: id
          in: query
          description: An award unique identifier to retrieve the information (ex. 1336650)
          required: false
          type: string
          x-graphVar: ?grantId

        # Awardee City
        - name: awardeeCity
          in: query
          description: Awardee city name(ex. Arlington)
          required: false
          type: string

        # Awardee Country Code
        - name: awardeeCountryCode
          in: query
          description: AU, CA, UK, US, USA, ...
          required: false
          type: string

        # Awardee Name
        - name: awardeeName
          in: query
          description: Name of the entity receiving award (ex, "university+of+south+florida")
          required: false
          type: string
          x-graphVar: ?institutionName

        # coPDPI
        - name: coPDPI
          in: query
          description: Co-Principal Investigator Name (ex. Christopher)
          required: false
          type: string
          x-graphVar: ?personName

        # Start date
        - name: startDate
          in: query
          description: Start date for award date to search. Accepted date format is mm/dd/yyyy (ex.12/31/2012)
          required: false
          type: string

        # End date
        - name: endDate
          in: query
          description: End date for award date to search. Accepted date format is mm/dd/yyyy (ex.12/31/2012)
          required: false
          type: string

        # Estimated total from amount
        - name: estimatedTotalAmtFrom
          in: query
          description: Estimated total from amount. This implies that you are searching for values greater than this amount. Results returned will be for values GREATER than the specified estimated amount (ex. 50000). For a range, you need to specify both the estimatedTotalAmtFrom and estimatedTotalAmtTo parameters
          required: false
          type: string

        # Estimated total to amount
        - name: estimatedTotalAmtTo
          in: query
          description: Estimated total to amount. This implies that you are searching for values less than this amount. Results returned will be for values LESS than the specified estimated amount (ex. 500000). For a range, you need to specify both the estimatedTotalAmtFrom and estimatedTotalAmtTo parameters
          required: false
          type: string

        # Funds obligated from amount
        - name: fundsObligatedAmtFrom
          in: query
          description: Funds obligated from amount. This implies that you are searching for values greater than this amount. Results returned will be for values GREATER than the specified estimated amount (ex. 50000). For a range, you need to specify both the estimatedTotalAmtFrom and estimatedTotalAmtTo parameters
          required: false
          type: string

        # Estimated total to amount
        - name: fundsObligatedAmtTo
          in: query
          description: Funds obligated to amount. This implies that you are searching for values less than this amount. Results returned will be for values LESS than the specified estimated amount (ex. 500000). For a range, you need to specify both the estimatedTotalAmtFrom and estimatedTotalAmtTo parameters
          required: false
          type: string

      x-responseMap:
        - var: ?grantId
          path: response/award/id
        - var: ?grantTitle
          path: response/award/title
        - var: ?grantDate
          path: response/award/date
        - var: ?amount
          path: response/award/fundsObligatedAmt
        - var: ?personFirstName
          path: response/award/piFirstName
        - var: ?personLastName
          path: response/award/piLastName
        - var: ?personName
          path: CONCAT(response/award/piFirstName, ' ', response/award/piLastName)
        - var: ?institutionName
          path: response/award/awardeeName
        - var: ?agencyName
          path: response/award/agency

      responses:
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/Response'


definitions:
  Response:
    properties:
      response:
        type: object
        properties:
          award:
            type: array
            items:
              type: object
              properties:
                agency:
                  type: string
                awardeeCity:
                  type: string
                awardeeName:
                  type: string
                awardeeStateCode:
                  type: string
                fundsObligatedAmt:
                  type: integer
                id:
                  type: integer
                piFirstName:
                  type: string
                piLastName:
                  type: string
                publicAccessMandate:
                  type: string
                date:
                  type: string
                  format: date
                title:
                  type: string
