swagger: '2.0'

info:
  version: "1.0.0"
  title: PubMed
  description: "
    The E-utilities are the public API to the NCBI Entrez system and allow access to all Entrez databases including PubMed, PMC, Gene, Nuccore and Protein. The E-utilities are a suite of eight server-side programs that accept a fixed URL syntax for search, link and retrieval operations. A companion package named Entrez Direct consists of several executables that allow the E-utilities to be called directly from a UNIX command line"

host: localhost
basePath: /lraeval/api/pubmed
schemes:
  - http
produces:
  - application/json
externalDocs:
  description: Documentation of the original data source
  url: https://www.ncbi.nlm.nih.gov/books/NBK25501/


paths:
  /esearch.json:
    get:
      summary: Text searches
      description: Responds to a text query with the list of matching UIDs in a given database (for later use in ESummary, EFetch or ELink), along with the term translations of the query.
      tags:
        - E-Utilities
      parameters:
        # Dataase
        - name: db
          in: query
          description: Database to search. Value must be a valid Entrez database name (default = pubmed). Full list at <a href="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi">https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi</a>
          required: false
          type: string
          default: pubmed

        # Term
        - name: term
          in: query
          description: Entrez text query. All special characters must be URL encoded. Spaces may be replaced by '+' signs. For very long queries (more than several hundred characters long), consider using an HTTP POST call. See the PubMed or Entrez help for information about search field descriptions and tags. Search fields and tags are database specific.
          required: true
          type: string

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ESearchResponse'

  /esummary.json:
    get:
      summary: Document summary downloads
      description: Responds to a list of UIDs from a given database with the corresponding document summaries.
      tags:
        - E-Utilities
      parameters:
        # Dataase
        - name: db
          in: query
          description: Database to search. Value must be a valid Entrez database name (default = pubmed). Full list at <a href="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi">https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi</a>
          required: false
          type: string
          default: pubmed

        # ID list
        - name: id
          in: query
          description: UID list. Either a single UID or a comma-delimited list of UIDs may be provided. All of the UIDs must be from the database specified by db. There is no set maximum for the number of UIDs that can be passed to ESummary, but if more than about 200 UIDs are to be provided, the request should be made using the HTTP POST method.
          required: true
          type: string
          collectionFormat: csv

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ESummaryResponse'

  /efetch.json:
    get:
      summary: Data record downloads
      description: Responds to a list of UIDs in a given database with the corresponding data records in a specified format.
      tags:
        - E-Utilities
      parameters:
        # Database
        - name: db
          in: query
          description: Database to search. Value must be a valid Entrez database name (default = pubmed). Full list at <a href="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi">https://eutils.ncbi.nlm.nih.gov/entrez/eutils/einfo.fcgi</a>
          required: false
          type: string
          default: pubmed

        # ID list
        - name: id
          in: query
          description: UID list. Either a single UID or a comma-delimited list of UIDs may be provided. All of the UIDs must be from the database specified by db. There is no set maximum for the number of UIDs that can be passed to ESummary, but if more than about 200 UIDs are to be provided, the request should be made using the HTTP POST method.
          required: true
          type: string
          collectionFormat: csv

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/EFetchResponse'

definitions:

  EFetchResponse:
    properties:
      entry:
        type: array
        items:
          $ref: '#/definitions/EntryRecord'

  EntryRecord:
    properties:
      pmid:
        type: integer
        format: int64
      medent:
        type: string
        format: date
      cit:
        $ref: '#/definitions/CitationInfo'
      abstract:
        type: string
      mesh:
        type: array
        items:
          properties:
            term:
              type: string
            qual:
              type: array
              items:
                properties:
                  mp:
                    type: string
                  subh:
                    type: string
      substance:
        type: array
        items:
          properties:
            type:
              type: string
            cit:
              type: string
            name:
              type: string
      pubtype:
        type: array
        items:
          type: string
      status:
        type: string

  CitationInfo:
    properties:
      title:
        type: object
        properties:
          name:
            type: string
      authors:
        type: object
        properties:
          names_std:
            type: array
            items:
              type: object
              properties:
                name_ml:
                  type: string
                affil_str:
                  type: string
      from_journal:
        type: object
        properties:
          title:
            type: object
            properties:
              iso-jta:
                type: string
              ml-jta:
                type: string
              issn:
                type: string
              name:
                type: string
      imp:
        type: object
        properties:
          date_std:
            type: string
            format: date
          volume:
            type: string
          issue:
            type: string
          pages:
            type: string
          language:
            type: string
          pubstatus:
            type: string
          history:
            type: array
            items:
              properties:
                pubstatus:
                  type: string
                date_std:
                  type: string
                  format: date-time
      ids:
        type: object
        properties:
          pubmed:
            type: integer
            format: int64
          pii:
            type: string
          doi:
            type: string

  ESummaryResponse:
    properties:
      DocSum:
        type: array
        items:
          $ref: '#/definitions/DocSummary'

  DocSummary:
    properties:
      Id:
        type: integer
        format: int64
      PubDate:
        type: string
      Source:
        type: string
      AuthorList:
        type: array
        items:
          type: string
      Title:
        type: string
      Volume:
        type: string
      Issue:
        type: string
      Pages:
        type: string
      LangList:
        type: array
        items:
          type: string
      NlmUniqueID:
        type: string
      ISSN:
        type: string
      PubType:
        type: string
      RecordStatus:
        type: string
      PubStatus:
        type: string
      ArticleIds:
        type: array
        items:
          properties:
            pubmed:
              type: string
            pii:
              type: string
            rid:
              type: string
            eid:
              type: string
      History:
        type: array
        items:
          properties:
            entrez:
              type: string
              format: date-time
            pubmed:
              type: string
              format: date-time
            medline:
              type: string
              format: date-time
      HasAbstract:
        type: string
      PmcRefCount:
        type: integer
        format: int64
      FullJournalName:
        type: string

  ESearchResponse:
    properties:
      Count:
        type: integer
        format: int64
      RetMax:
        type: integer
        format: int64
      RetStart:
        type: integer
        format: int64
      QueryKey:
        type: string
      WebEnv:
        type: string
      IdList:
        type: array
        items:
          type: string
      TranslationSet:
        type: array
        items:
          $ref: '#/definitions/TranslationItem'
      TranslationStack:
        type: object
        properties:
          TermSet:
            type: array
            items:
              $ref: '#/definitions/TermItem'
          OP:
            type: array
            items:
              type: string
      QueryTranslation:
        type: string

  TranslationItem:
    properties:
      From:
        type: string
      To:
        type: string

  TermItem:
    properties:
      Term:
        type: string
      Field:
        type: string
      Count:
        type: string
      Explode:
        type: string

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
